blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [

    path("",views.all_blogs, name = 'all_blogs'),
    path("<int:blog_id>/",views.detail, name = 'detail'),

]

generator/urls.py
from django.urls import path
from . import views
app_name = 'generator'

urlpatterns = [

    path("",views.password_generator, name = "password_generator"),
    path("password/",views.password, name = "password"),
    path("about/",views.about, name = "about"),


]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",views.home, name = 'home'),
    path('blog/', include('blog.urls')),
    path('generator/', include('generator.urls')),
    path('utilities/', include('utilities.urls')),
    path('todo/', include('todo.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

generator/views.py
from django.shortcuts import render
from django.http import HttpResponse
import random

def password_generator(request):
    return render(request,"generator/password_generator.html")

def password(request):

    characters = list ("abcdefghijklmnopqrstuvwxyz")
    length = int(request.GET.get('length',12))

    if request.GET.get("uppercase"):
        characters.extend(list('ABCDEFGHIJKLMNOPQRSTUVWXYZ'))

    if request.GET.get("special"):
        characters.extend(list('+_)(*&^%$#@!~'))

    if request.GET.get("numbers"):
        characters.extend(list('1234567890'))

    thepassword = ""
    for x in range(length):
        thepassword += random.choice(characters)

    return render(request,"generator/password.html",{"password":thepassword})

def about(request):
    return render(request, "generator/about.html")

generator/templates/generator/about.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class = "container text-center">

<h1>About me:</h1>
<p>I am Christopher M. Esmeres, a certified public accountant
    Want to excel in Django!
</p>
<br>
<br>
<a href="{% url "generator:password_generator" %}"  class = "btn btn-warning" >Home</a>

generator/templates/generator/password.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<div class = "container text-center">

<h1>Your password is:</h1>
<h2 class="alert alert-success" >{{password}}</h2>
<br>
<a href="{% url "generator:password_generator" %}"  class = "btn btn-warning" >Home</a>

</div>

generator/templates/generator/password_generator.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<div class = "container text-center">
<h1>Password Generator</h1>

<form action="{%url "generator:password"%}">
    <select name = "length">
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
        <option value="11">11</option>
        <option value="12" selected="selected">12</option>
        <option value="13">13</option>
        <option value="14">14</option>
    </select> Length
    <br>
    <input type="checkbox" name = "uppercase"> Uppercase
    <br>
    <input type="checkbox" name = "numbers"> Numbers
    <br>
    <input type="checkbox" name = "special"> Special Characters
    <br>

    <input type = "submit" value = "Generate Password" class="btn btn-primary" >
<br>
<br>
<br>
<a href={% url "generator:about" %}>About Me</a>

</form>
</div>